[workspace]
members = ["client", "worker", "crab_master", "common"]

[workspace.dependencies]
tonic = "*"
prost = "0.13"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
common = { path = "../common" }
anyhow = "1.0.98"
thiserror = "2"
