[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "*"
prost = "0.13"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
common = { path = "../common" }
anyhow = "1.0.98"

[build-dependencies]
tonic-build = "*"
